use std::{
    env,
    fs::{self, OpenOptions},
    io::ErrorKind,
    net::SocketAddr,
    path::{Path, PathBuf},
    process::{Command, Stdio},
    thread,
    time::{Duration, Instant},
};

use anyhow::{Context, Result, anyhow, bail};
use chrono::Local;

use crate::{auth::password_hash_from_input, daemon};

const CONFIG_PATH: &str = "config/local.toml";
const DEFAULT_LISTEN: &str = "127.0.0.1:8010";
const TAILSCALE_STATE_DIR: &str = ".local/share/tailscale-obr";
const TAILSCALE_SOCKET: &str = "tailscaled.sock";
const TAILSCALE_PID: &str = "tailscaled.pid";
const TAILSCALE_LOG: &str = "tailscaled.log";
const TAILSCALE_LOGIN_TIMEOUT: Duration = Duration::from_secs(5 * 60);
const TAILSCALED_START_TIMEOUT: Duration = Duration::from_secs(10);
const POLL_INTERVAL: Duration = Duration::from_millis(500);

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct InitOptions {
    pub(crate) vault_path: PathBuf,
    pub(crate) tailscale: bool,
    pub(crate) hostname: String,
}

struct TailscaleSetup {
    tailscale: PathBuf,
    tailscaled: PathBuf,
    state_dir: PathBuf,
    socket: PathBuf,
    hostname: String,
}

pub(crate) fn run(options: InitOptions) -> Result<()> {
    validate_hostname(&options.hostname)?;
    let vault_path = prepare_vault_path(&options.vault_path)?;

    println!("Creating Obr config for vault: {}", vault_path.display());
    println!("Choose the admin password for Obr.");
    let password_hash = password_hash_from_input().context("read Obr password")?;

    let public_host = if options.tailscale {
        Some(configure_tailscale(&options.hostname)?)
    } else {
        None
    };

    write_config(&vault_path, &password_hash, public_host.as_deref())?;

    println!("Starting Obr daemon...");
    daemon::reload()?;

    println!();
    println!("Obr is ready.");
    println!("Local URL: {}", local_url(DEFAULT_LISTEN));
    if let Some(host) = public_host {
        println!("Tailscale URL: https://{host}/");
    }
    println!("Config: {CONFIG_PATH}");
    Ok(())
}

fn prepare_vault_path(path: &Path) -> Result<PathBuf> {
    let path = if path.is_absolute() {
        path.to_path_buf()
    } else {
        env::current_dir()?.join(path)
    };
    fs::create_dir_all(&path).with_context(|| format!("create vault {}", path.display()))?;
    path.canonicalize()
        .with_context(|| format!("resolve vault {}", path.display()))
}

fn write_config(vault_path: &Path, password_hash: &str, public_host: Option<&str>) -> Result<()> {
    let config_path = Path::new(CONFIG_PATH);
    if let Some(parent) = config_path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    }
    if let Some(backup) = backup_existing_config(config_path)? {
        println!("Existing config backed up to {}", backup.display());
    }

    let rendered = render_config(vault_path, password_hash, public_host)?;
    fs::write(config_path, rendered).with_context(|| format!("write {CONFIG_PATH}"))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut permissions = fs::metadata(config_path)?.permissions();
        permissions.set_mode(0o600);
        fs::set_permissions(config_path, permissions)?;
    }

    println!("Wrote {CONFIG_PATH}");
    Ok(())
}

fn backup_existing_config(config_path: &Path) -> Result<Option<PathBuf>> {
    if !config_path.exists() {
        return Ok(None);
    }
    let timestamp = Local::now().format("%Y%m%d%H%M%S");
    let backup = config_path.with_extension(format!("toml.bak-{timestamp}"));
    fs::copy(config_path, &backup)
        .with_context(|| format!("backup {} to {}", config_path.display(), backup.display()))?;
    Ok(Some(backup))
}

fn render_config(
    vault_path: &Path,
    password_hash: &str,
    public_host: Option<&str>,
) -> Result<String> {
    let vault_path = vault_path
        .to_str()
        .ok_or_else(|| anyhow!("vault path is not valid UTF-8: {}", vault_path.display()))?;
    let secure_cookies = public_host.is_some();
    let mut config = format!(
        r#"# Generated by `obr init`.
listen = "127.0.0.1:8010"
vault_path = "{vault_path}"
daily_dir = "Daily"
entry_dir = "Posts"
image_dir = "Pics"
todo_path = "Posts/todo.md"
log_path = "logs/obr.log"
log_level = "info"
username = "admin"
password_hash = "{password_hash}"
allow_plaintext_password = false
session_days = 21
secure_cookies = {secure_cookies}
auto_git_sync = false
rss_enabled = false
rss_feeds_path = "Zero/feeds.md"
rss_data_dir = "data/rss"
rss_refresh_minutes = 30
rss_max_items_per_feed = 20
rss_fetch_full_content = true
rss_ai_summary_enabled = true
rss_ai_summary_chars = 200
deepseek_api_base = "https://api.deepseek.com"
deepseek_model = "deepseek-v4-flash"
passkey_store_path = "data/passkeys.json"
webauthn_rp_name = "Obr"
"#,
        vault_path = toml_string(vault_path),
        password_hash = toml_string(password_hash),
    );
    if let Some(host) = public_host {
        config.push_str(&format!("webauthn_rp_id = \"{}\"\n", toml_string(host)));
    }
    Ok(config)
}

fn toml_string(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

fn configure_tailscale(hostname: &str) -> Result<String> {
    let setup = TailscaleSetup::new(hostname)?;
    ensure_tailscaled(&setup)?;
    login_tailscale(&setup)?;
    wait_for_tailscale_login(&setup)?;
    configure_funnel(&setup)?;
    let host = funnel_host(&setup)?;
    println!("Tailscale Funnel is ready: https://{host}/");
    Ok(host)
}

impl TailscaleSetup {
    fn new(hostname: &str) -> Result<Self> {
        let state_dir = home_dir()?.join(TAILSCALE_STATE_DIR);
        Ok(Self {
            tailscale: tailscale_binary(),
            tailscaled: tailscaled_binary(),
            socket: state_dir.join(TAILSCALE_SOCKET),
            state_dir,
            hostname: hostname.to_string(),
        })
    }
}

fn home_dir() -> Result<PathBuf> {
    env::var_os("HOME")
        .map(PathBuf::from)
        .ok_or_else(|| anyhow!("HOME is not set"))
}

fn tailscale_binary() -> PathBuf {
    env::var_os("OBR_TAILSCALE")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            first_existing(&[
                "/opt/homebrew/opt/tailscale/bin/tailscale",
                "/usr/local/bin/tailscale",
                "tailscale",
            ])
        })
}

fn tailscaled_binary() -> PathBuf {
    env::var_os("OBR_TAILSCALED")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            first_existing(&[
                "/opt/homebrew/opt/tailscale/bin/tailscaled",
                "/usr/local/bin/tailscaled",
                "tailscaled",
            ])
        })
}

fn first_existing(candidates: &[&str]) -> PathBuf {
    candidates
        .iter()
        .find(|candidate| candidate.starts_with('/') && Path::new(candidate).exists())
        .unwrap_or_else(|| candidates.last().expect("at least one candidate"))
        .into()
}

fn ensure_tailscaled(setup: &TailscaleSetup) -> Result<()> {
    fs::create_dir_all(&setup.state_dir)
        .with_context(|| format!("create {}", setup.state_dir.display()))?;
    if tailscale_socket_ready(setup) {
        println!(
            "Tailscale daemon already running at {}",
            setup.socket.display()
        );
        return Ok(());
    }
    remove_stale_socket(&setup.socket)?;

    println!("Starting Tailscale daemon at {}", setup.state_dir.display());
    let log = OpenOptions::new()
        .create(true)
        .append(true)
        .open(setup.state_dir.join(TAILSCALE_LOG))
        .with_context(|| format!("open {}", setup.state_dir.join(TAILSCALE_LOG).display()))?;
    let stderr = log.try_clone().context("clone tailscaled log file")?;

    let mut command = Command::new(&setup.tailscaled);
    command
        .arg("--tun=userspace-networking")
        .arg("--socket")
        .arg(&setup.socket)
        .arg("--statedir")
        .arg(&setup.state_dir)
        .stdin(Stdio::null())
        .stdout(Stdio::from(log))
        .stderr(Stdio::from(stderr));

    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        unsafe {
            command.pre_exec(|| {
                if libc::setsid() == -1 {
                    return Err(std::io::Error::last_os_error());
                }
                Ok(())
            });
        }
    }

    let mut child = command
        .spawn()
        .with_context(|| format!("start {}", setup.tailscaled.display()))?;
    fs::write(
        setup.state_dir.join(TAILSCALE_PID),
        format!("{}\n", child.id()),
    )
    .with_context(|| format!("write {}", setup.state_dir.join(TAILSCALE_PID).display()))?;

    let deadline = Instant::now() + TAILSCALED_START_TIMEOUT;
    while Instant::now() < deadline {
        if let Some(status) = child
            .try_wait()
            .context("check tailscaled startup status")?
        {
            bail!("tailscaled exited immediately with {status}");
        }
        if tailscale_socket_ready(setup) {
            return Ok(());
        }
        thread::sleep(POLL_INTERVAL);
    }
    bail!(
        "tailscaled did not become ready; see {}",
        setup.state_dir.join(TAILSCALE_LOG).display()
    )
}

fn remove_stale_socket(socket: &Path) -> Result<()> {
    match fs::remove_file(socket) {
        Ok(()) => Ok(()),
        Err(err) if err.kind() == ErrorKind::NotFound => Ok(()),
        Err(err) => Err(err).with_context(|| format!("remove stale socket {}", socket.display())),
    }
}

fn tailscale_socket_ready(setup: &TailscaleSetup) -> bool {
    let output = Command::new(&setup.tailscale)
        .arg("--socket")
        .arg(&setup.socket)
        .arg("status")
        .output();
    let Ok(output) = output else {
        return false;
    };
    if output.status.success() {
        return true;
    }
    let message = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    !(message.contains("dial unix")
        || message.contains("connect: no such file")
        || message.contains("connection refused")
        || message.contains("failed to connect"))
}

fn login_tailscale(setup: &TailscaleSetup) -> Result<()> {
    println!("Logging this Tailscale node in as `{}`.", setup.hostname);
    println!("If Tailscale prints a login URL, open it, approve the node, then return here.");
    let status = Command::new(&setup.tailscale)
        .arg("--socket")
        .arg(&setup.socket)
        .arg("up")
        .arg("--hostname")
        .arg(&setup.hostname)
        .arg("--accept-dns=false")
        .status()
        .context("run tailscale up")?;
    if !status.success() {
        bail!("tailscale up exited with {status}");
    }
    Ok(())
}

fn wait_for_tailscale_login(setup: &TailscaleSetup) -> Result<()> {
    let deadline = Instant::now() + TAILSCALE_LOGIN_TIMEOUT;
    while Instant::now() < deadline {
        let output = Command::new(&setup.tailscale)
            .arg("--socket")
            .arg(&setup.socket)
            .arg("status")
            .output()
            .context("run tailscale status")?;
        let combined = format!(
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        if output.status.success()
            && !combined.contains("Logged out")
            && !combined.contains("NeedsLogin")
        {
            return Ok(());
        }
        thread::sleep(Duration::from_secs(2));
    }
    bail!("timed out waiting for Tailscale login")
}

fn configure_funnel(setup: &TailscaleSetup) -> Result<()> {
    let target = format!("http://{DEFAULT_LISTEN}");
    println!("Enabling Tailscale Funnel for {target}");
    let status = Command::new(&setup.tailscale)
        .arg("--socket")
        .arg(&setup.socket)
        .arg("funnel")
        .arg("--yes")
        .arg("--bg")
        .arg(&target)
        .status()
        .context("run tailscale funnel")?;
    if !status.success() {
        bail!("tailscale funnel exited with {status}");
    }
    Ok(())
}

fn funnel_host(setup: &TailscaleSetup) -> Result<String> {
    let output = Command::new(&setup.tailscale)
        .arg("--socket")
        .arg(&setup.socket)
        .arg("funnel")
        .arg("status")
        .output()
        .context("run tailscale funnel status")?;
    if !output.status.success() {
        bail!(
            "tailscale funnel status exited with {}; {}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        );
    }
    let stdout = String::from_utf8_lossy(&output.stdout);
    parse_funnel_host(&stdout).ok_or_else(|| {
        anyhow!(
            "could not find Funnel hostname in `tailscale funnel status` output:\n{}",
            stdout
        )
    })
}

fn parse_funnel_host(status: &str) -> Option<String> {
    for word in status.split_whitespace() {
        let word = word.trim_matches(|ch| matches!(ch, '(' | ')' | ',' | ';'));
        let Ok(url) = url::Url::parse(word) else {
            continue;
        };
        if url.scheme() == "https"
            && let Some(host) = url.host_str()
        {
            return Some(host.to_string());
        }
    }
    None
}

fn validate_hostname(hostname: &str) -> Result<()> {
    if hostname.is_empty() {
        bail!("hostname cannot be empty");
    }
    if hostname.starts_with('-') || hostname.ends_with('-') {
        bail!("hostname cannot start or end with '-'");
    }
    if !hostname
        .chars()
        .all(|ch| ch.is_ascii_alphanumeric() || ch == '-')
    {
        bail!("hostname can only contain ASCII letters, digits, and '-'");
    }
    Ok(())
}

fn local_url(listen: &str) -> String {
    match listen.parse::<SocketAddr>() {
        Ok(addr) if addr.ip().is_loopback() => format!("http://localhost:{}/", addr.port()),
        Ok(addr) => format!("http://{addr}/"),
        Err(_) => format!("http://{listen}/"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_funnel_hostname_from_status() {
        let status = r#"
# Funnel on:
#     - https://ob.example.ts.net

https://ob.example.ts.net (Funnel on)
|-- / proxy http://127.0.0.1:8010
"#;

        assert_eq!(
            parse_funnel_host(status).as_deref(),
            Some("ob.example.ts.net")
        );
    }

    #[test]
    fn rendered_tailscale_config_uses_https_rp_id_default() {
        let config = render_config(
            Path::new("/tmp/vault"),
            "$argon2id$example",
            Some("ob.example.ts.net"),
        )
        .unwrap();

        assert!(config.contains("secure_cookies = true"));
        assert!(config.contains(r#"webauthn_rp_id = "ob.example.ts.net""#));
        assert!(!config.contains("webauthn_origin"));
    }
}
